# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "chats", :force => true do |t|
    t.string   "name"
    t.text     "message"
    t.string   "password"
    t.datetime "created_at"
  end

  create_table "meteors", :force => true do |t|
    t.text     "javascript"
    t.integer  "limit"
    t.datetime "created_at"
  end

end
