# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "chats", :force => true do |t|
    t.column "name",       :string
    t.column "message",    :text
    t.column "password",   :string
    t.column "created_at", :datetime
  end

  create_table "meteors", :force => true do |t|
    t.column "javascript", :text
    t.column "limit",      :integer
    t.column "created_at", :datetime
  end

end
